OLH-1128: updated from alphagov to govuk-one-login
govuk-one-login/di-account-management-backend pull request #170
Opened 2023-12-11 16:04 UTC by TaherKapasi

## Proposed changes

### What changed
As part of transferring ownership of repo from alphagov to govuk-one-login (a trust initiative) this PR has updated any old package references to point to new location.

### Why did it change
A Trust Initiative

### Related links
[OLH-1128](https://govukverify.atlassian.net/browse/OLH-1128)

## Checklists
Github actions, templates, references and repo

### Environment variables or secrets
- [x] No environment variables or secrets were added or changed

## Testing
N/A

[OLH-1128]: https://govukverify.atlassian.net/browse/OLH-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-11 16:15 UTC, domantas-gds approved these changes

2023-12-11 16:22 UTC, domantas-gds commented on CODEOWNERS
> -* @alphagov/one-login-home-developers
CODEOWNERS contains errors?

2023-12-11 16:23 UTC, domantas-gds requested changes
Need to update CODEOWNERS to @govuk-one-login/one-login-home-dev

2023-12-11 16:25 UTC, domantas-gds commented on CODEOWNERS
> +* @govuk-one-login/one-login-home-developers
```suggestion
* @govuk-one-login/one-login-home-dev
```

2024-04-30 08:29 UTC, closed without merging

2024-04-30 08:29 UTC, alex9smith commented
I'm going to close this. There's been so many changes since that it'll be easier to start from scratch